# Generated by Django 4.2.2 on 2023-06-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_message_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['host', 'topic', 'name', 'description', 'created', 'updated']},
        ),
    ]
